# Generated by Django 4.1.2 on 2024-10-30 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=8)),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='image/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glownaturals.usuario')),
            ],
        ),
    ]
